#235: optinal BankConnection.owners()
proshin-roman/finapi-java-client pull request #355
Opened 2020-11-20 22:43 UTC by ccostin93

2020-11-20 23:24 UTC, ccostin93 commented
@proshin-roman Unfortunately, this is a breaking change. I had to change 
`Iterable<Owner> BC.owners` to `Optional<Iterable<Owner>> BC.owners`

2020-11-21 12:41 UTC, proshin-roman requested changes

2020-11-21 12:41 UTC, proshin-roman commented on src/main/java/org/proshin/finapi/bankconnection/FpBankConnection.java
> +    public Optional<Iterable<Owner>> owners() {
Optional of Iterable doesn't make much sense as the iterable itself can be empty. Let's maybe map `null` value to an empty Iterable?

2020-11-21 13:02 UTC, proshin-roman approved these changes

2020-11-21 13:20 UTC, ccostin93 commented
@dependabot squash and merge

2020-11-21 13:22 UTC, ccostin93 commented
@rultor merge

2020-11-21 13:23 UTC, rultor commented
> @rultor merge

@ccostin93 Thanks for your request. @proshin-roman Please confirm this.

2020-11-21 13:26 UTC, proshin-roman commented
@rultor confirm

2020-11-21 13:27 UTC, rultor commented
> @rultor confirm

@proshin-roman I'm sorry, I don't understand you :( Check [this page](http://doc.rultor.com/basics.html) and try again please

2020-11-21 13:28 UTC, merged